# file: postgresql/tasks/configure.yml

- name: PostgreSQL | Drop the data directory | RedHat
  ansible.builtin.file:
    path: "{{ postgresql_data_directory }}"
    state: absent
  register: pgdata_dir_remove
  when:
    - ansible_facts['os_family'] == 'RedHat'
    - (postgresql_cluster_reset | default(false)) | bool

- name: PostgreSQL | Make sure the postgres data directory exists
  file:
    path: "{{postgresql_data_directory}}"
    owner: "{{ postgresql_service_user }}"
    group: "{{ postgresql_service_group }}"
    state: directory
    mode: 0700
  register: pgdata_dir_exist

- name: PostgreSQL | Make sure postgres tablespaces directories exist
  file:
    path: "{{ item }}"
    owner: "{{ postgresql_service_user }}"
    group: "{{ postgresql_service_group }}"
    state: directory
    mode: 0700
  with_items: "{{ postgresql_tablespaces_dirs }}"

- name: PostgreSQL | Make sure the postgres WAL directory exists
  file:
    path: "{{ postgresql_wal_directory }}"
    owner: "{{ postgresql_service_user }}"
    group: "{{ postgresql_service_group }}"
    state: directory
    mode: 0700
  register: pgwal_dir_exist
  when: postgresql_wal_directory != ""

- name: PostgreSQL | Make sure the postgres log directory exists
  file:
    path: "{{ postgresql_log_directory }}"
    owner: "{{ postgresql_service_user }}"
    group: "{{ postgresql_service_group }}"
    state: directory
    mode: 0700
  register: pglog_dir_exist
  when: postgresql_log_directory != "pg_log" or postgresql_log_directory != "log"

- name: PostgreSQL | Ensure locales for lc_collate and lc_ctype are generated | Debian
  become: true
  ansible.builtin.locale_gen:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ postgresql_locale }}"
    - "{{ postgresql_ctype }}"
  when:
    - ansible_facts['os_family'] == 'Debian'
    - item != 'C.UTF-8'

- name: PostgreSQL | Ensure the locale is generated | RedHat
  become: true
  ansible.builtin.command:
    cmd: >-
      localedef -c -i {{ item.parts[0] }} -f {{ item.parts[1] }} {{ item.locale_name }}
  changed_when: false
  loop:
    - { parts: "{{ postgresql_locale_parts }}", locale_name: "{{ postgresql_locale }}" }
    - { parts: "{{ postgresql_ctype_parts }}", locale_name: "{{ postgresql_ctype }}" }
  when:
    - ansible_facts['os_family'] == 'RedHat'
  ignore_errors: true

- name: PostgreSQL | Stop PostgreSQL | Debian
  become: true
  ansible.builtin.service:
    name: "{{ postgresql_service_name }}"
    state: stopped
  when:
    - ansible_facts['os_family'] == 'Debian'
    - (postgresql_cluster_reset | default(false)) | bool
    - (pgdata_dir_exist.changed | default(false)) | bool

- name: PostgreSQL | Reset the cluster - drop the existing one | Debian
  become: true
  become_user: "{{ postgresql_service_user }}"
  ansible.builtin.shell: >-
    pg_dropcluster {{ postgresql_version }} {{ postgresql_cluster_name }}
  args:
    warn: false
  when:
    - ansible_facts['os_family'] == 'Debian'
    - (postgresql_cluster_reset | default(false)) | bool
    - (pgdata_dir_exist.changed | default(false)) | bool

- name: PostgreSQL | Reset the cluster - create a new one (with specified encoding and locale) | Debian
  become: true
  become_user: "{{ postgresql_service_user }}"
  ansible.builtin.shell: >-
    pg_createcluster
    --locale {{ postgresql_locale | quote }}
    -e {{ postgresql_encoding | quote }}
    -d {{ postgresql_data_directory | quote }}
    {{ postgresql_version | quote }} {{ postgresql_cluster_name | quote }}
    --
    {% if (postgresql_data_checksums | default(false)) | bool and postgresql_version is version('9.3', '>=') -%}
    --data-checksums
    {%- endif -%}
    {% if (postgresql_pwfile | default('')) | length > 0 -%}
    --pwfile={{ postgresql_pwfile | quote }}
    {%- endif -%}
    {% if (postgresql_wal_directory | default('')) | length > 0 and postgresql_version is version('10', '<') -%}
    --xlogdir={{ postgresql_wal_directory | quote }}
    {%- endif -%}
    {% if (postgresql_wal_directory | default('')) | length > 0 and postgresql_version is version('10', '>=') -%}
    --waldir={{ postgresql_wal_directory | quote }}
    {%- endif -%}
  args:
    warn: false
  when:
    - ansible_facts['os_family'] == 'Debian'
    - (postgresql_cluster_reset | default(false)) | bool
    - (pgdata_dir_exist.changed | default(false)) | bool

- name: PostgreSQL | Update systemd | Debian
  become: true
  ansible.builtin.command: systemctl daemon-reload
  args:
    warn: false
  when:
    - ansible_facts['os_family'] == 'Debian'
    - (postgresql_cluster_reset | default(false)) | bool
    - (pgdata_dir_exist.changed | default(false)) | bool

- name: PostgreSQL | Start PostgreSQL | Debian
  become: true
  ansible.builtin.service:
    name: "{{ postgresql_service_name }}"
    state: started
  when:
    - ansible_facts['os_family'] == 'Debian'
    - (postgresql_cluster_reset | default(false)) | bool
    - (pgdata_dir_exist.changed | default(false)) | bool

- name: PostgreSQL | Check whether the postgres data directory is initialized | RedHat
  ansible.builtin.stat:
    path: "{{ postgresql_data_directory }}/PG_VERSION"
  register: pgdata_dir_initialized
  when:
    - ansible_facts['os_family'] == 'RedHat'
    - not ((postgresql_cluster_reset | default(false)) | bool)

- name: PostgreSQL | Initialize the database | RedHat
  become: true
  become_user: "{{ postgresql_service_user }}"
  ansible.builtin.command: >-
    {{ postgresql_bin_directory | quote }}/initdb
    -D {{ postgresql_data_directory | quote }}
    --locale={{ postgresql_locale | quote }}
    --encoding={{ postgresql_encoding | quote }}
    {% if (postgresql_data_checksums | default(false)) | bool and postgresql_version is version('9.3', '>=') -%}
    --data-checksums
    {%- endif -%}
    {% if (postgresql_pwfile | default('')) | length > 0 -%}
    --pwfile={{ postgresql_pwfile | quote }}
    {%- endif -%}
    {% if (postgresql_wal_directory | default('')) | length > 0 and postgresql_version is version('10', '<') -%}
    --xlogdir={{ postgresql_wal_directory | quote }}
    {%- endif -%}
    {% if (postgresql_wal_directory | default('')) | length > 0 and postgresql_version is version('10', '>=') -%}
    --waldir={{ postgresql_wal_directory | quote }}
    {%- endif -%}
    {% if (postgresql_wal_segsize | default('')) | length > 0 and postgresql_version is version('11', '>=') -%}
    --wal-segsize={{ postgresql_wal_segsize | quote }}
    {%- endif -%}
  args:
    warn: false
  when:
    - ansible_facts['os_family'] == 'RedHat'
    - (postgresql_cluster_reset | default(false)) | bool
      or (pgdata_dir_exist.changed | default(false)) | bool
      or (not (pgdata_dir_initialized.stat.exists | default(false)))

- name: PostgreSQL | Verify postgresql cluster version
  command: grep ^{{ postgresql_version }}$ {{ postgresql_data_directory }}/PG_VERSION
  changed_when: false

- name: PostgreSQL | Ensure configuration directory exists
  file:
    path: "{{ postgresql_conf_directory }}"
    owner: "{{ postgresql_service_user }}"
    group: "{{ postgresql_service_group }}"
    mode: 0700
    state: directory

- name: PostgreSQL | Update configuration - pt. 1 (pg_hba.conf)
  template:
    src: pg_hba.conf.j2
    dest: "{{postgresql_conf_directory}}/pg_hba.conf"
    owner: "{{ postgresql_service_user }}"
    group: "{{ postgresql_service_group }}"
    mode: 0640
  no_log: "{{ postgresql_hide_passwords }}"
  register: postgresql_configuration_pt1

- name: PostgreSQL | Update configuration - pt. 2 (postgresql.conf)
  ansible.builtin.template:
    src: "postgresql.conf-{{ postgresql_version }}.j2"
    # If pgtune is enabled, write the base template to ".untuned"
    dest: "{{ postgresql_conf_directory }}/postgresql.conf{% if (postgresql_pgtune | default(false)) | bool %}.untuned{% endif %}"
    owner: "{{ postgresql_service_user }}"
    group: "{{ postgresql_service_group }}"
    mode: "0640"          # quotes prevent YAML from misreading octal notation
    backup: true          # automatically saves a timestamped copy before overwriting
  register: postgresql_configuration_pt2
  notify:
    - restart postgresql  # triggers the handler only if this file changed

- name: PostgreSQL | Update configuration - pt. 3 (pgtune)
  become: true
  become_user: "{{ postgresql_service_user }}"
  shell: |
    set -e
    TMPDIR=$(mktemp -d)
    pgtune --input-config=postgresql.conf.untuned\
           --output-config=$TMPDIR/postgresql.conf\
           {% if postgresql_pgtune_memory %}--memory {{postgresql_pgtune_memory|int}}{% endif %}\
           --type {{postgresql_pgtune_type|quote}}\
           {% if postgresql_pgtune_connections %}--connections {{postgresql_pgtune_connections|int}}{% endif %}\
    # Compare the current config with the one procuded by pgtune (ignoring comments/blanks)
    if diff --ignore-blank-lines \
        <(sed -e 's/#.*//' postgresql.conf) \
        <(sed -e 's/#.*//' $TMPDIR/postgresql.conf)
    then
      echo '_OK_'
    else
      cp $TMPDIR/postgresql.conf postgresql.conf
    fi
    # Cleanup
    rm $TMPDIR/postgresql.conf
    rmdir $TMPDIR
  args:
    chdir: "{{postgresql_conf_directory}}"
    executable: "/bin/bash"
  when: postgresql_pgtune
  register: postgresql_configuration_pt3
  changed_when: "'_OK_' not in postgresql_configuration_pt3.stdout"

- name: PostgreSQL | Update configuration - pt. 4 (pg_ident.conf)
  template:
    src: pg_ident.conf.j2
    dest: "{{ postgresql_ident_file }}"
    owner: "{{ postgresql_service_user }}"
    group: "{{ postgresql_service_group }}"
    mode: 0640
  register: postgresql_configuration_pt4
  notify: restart postgresql

- name: PostgreSQL | Create folder for additional configuration files
  file:
    name: "{{postgresql_conf_directory}}/conf.d"
    state: directory
    owner: "{{ postgresql_service_user }}"
    group: "{{ postgresql_service_group }}"
    mode: 0755

- name: PostgreSQL | Ensure the systemd directory for PostgreSQL exists | RedHat
  ansible.builtin.file:
    path: "/etc/systemd/system/postgresql-{{ postgresql_version }}.service.d"
    state: directory
    mode: "0755"
  when:
    - ansible_facts['os_family'] == 'RedHat'
  notify: restart postgresql

- name: PostgreSQL | Use the conf directory when starting the Postgres service | RedHat
  ansible.builtin.template:
    src: etc_systemd_system_postgresql.service.d_custom.conf.j2
    dest: "/etc/systemd/system/postgresql-{{ postgresql_version }}.service.d/custom.conf"
    owner: root
    group: root
    mode: "0644"
  when:
    - ansible_facts['os_family'] == 'RedHat'
  register: postgresql_systemd_custom_conf
  notify: restart postgresql

- name: PostgreSQL | Ensure the pid directory for PostgreSQL exists
  file:
    name: "{{ postgresql_pid_directory }}"
    state: directory
    owner: "{{ postgresql_service_user }}"
    group: "{{ postgresql_service_group }}"
    mode: u=rwX,g=rwXs,o=rx
  notify: restart postgresql

- block:
  - name: PostgreSQL | Ensure PostgreSQL is running
    service:
      name: "{{ postgresql_service_name }}"
      state: started
    register: postgresql_cold_started

  - name: PostgreSQL | Reload PostgreSQL configuration
    service:
      name: "{{ postgresql_service_name }}"
      state: reloaded
    register: postgresql_reloaded
    when: not postgresql_cold_started.changed
  when: postgresql_configuration_pt1.changed or postgresql_configuration_pt2.changed or postgresql_configuration_pt3.changed or postgresql_systemd_custom_conf.changed
