# file: postgresql/tasks/users_privileges.yml
# Make sure the service is running first
- name: PostgreSQL | Ensure PostgreSQL is running
  service:
    name: "{{ postgresql_service_name }}"
    state: started

# Grant database-level privileges
- name: PostgreSQL | Grant database privileges
  community.postgresql.postgresql_privs:
    type: database
    login_db: "{{ item.db }}"               # database to grant on
    roles: "{{ item.name }}"          # role receiving privileges
    privs: "{{ item.privs | default('ALL') }}"
    grant_option: "{{ item.grant_option | default(omit) }}"
    state: present
    login_user: "{{ postgresql_admin_user }}"
    login_password: "{{ postgresql_admin_password | default(omit) }}"
    login_host: "{{ item.host | default(omit) }}"
    login_port: "{{ postgresql_port }}"
  become: yes
  become_user: "{{ postgresql_admin_user }}"
  loop: "{{ postgresql_user_privileges | default([]) }}"
  when: (postgresql_user_privileges | default([])) | length > 0
