# file: postgresql/handlers/main.yml

  - name: restart postgresql
    service:
      name: "{{ postgresql_service_name }}"
      state: restarted
      enabled: yes

  - name: Reload systemd daemon
    ansible.builtin.command: systemctl daemon-reload
    become: true
