---
name: CI
'on':
  pull_request:
    branches:
      - master
      - development
  push:
    branches:
      - development
      - decrease-ansible-deprecation-5-0-0
  schedule:
    - cron: "0 4 * * 4"

defaults:
  run:
    working-directory: 'postgresql'

jobs:

  lint:
    name: Yamllint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4
        with:
          path: 'postgresql'

      - name: Set up Python.
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: pip3 install yamllint

      - name: Lint code.
        run: |
          yamllint .

  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # - distro: rockylinux8
          # - distro: rockylinux9
          - distro: debian11
          - distro: debian12
          - distro: ubuntu2204
          - distro: ubuntu2404

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4
        with:
          path: 'postgresql'

      - name: Set up Python.
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Upgrade pip & install deps
        run: |
          python -m pip install --upgrade pip wheel setuptools
          # Meta-package Ansible 10/11 (include ansible-core â‰¥2.20)
          pip install "ansible>10,<12"
          # Testing tools
          pip install "molecule" "molecule-plugins[docker]" docker ansible-compat

      - name: Show versions
        run: |
          python -V
          ansible --version
          molecule --version

      - name: Run Molecule tests.
        run: molecule -v test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
          MOLECULE_PLAYBOOK: ${{ matrix.playbook }}
